apiVersion: v2
name: keycloak-operator
description: A Kubernetes operator for managing Keycloak resources
type: application
version: 0.3.0
appVersion: 0.3.0
kubeVersion: ">=1.25.0-0"
home: https://github.com/Hostzero-GmbH/keycloak-operator
sources:
  - https://github.com/Hostzero-GmbH/keycloak-operator
keywords:
  - keycloak
  - operator
  - identity
  - authentication
  - oauth
  - oidc
maintainers:
  - name: HostZero
    url: https://hostzero.com
