apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/keycloak.hostzero.com_keycloakinstances.yaml
  - bases/keycloak.hostzero.com_keycloakrealms.yaml
  - bases/keycloak.hostzero.com_keycloakclients.yaml
  - bases/keycloak.hostzero.com_keycloakusers.yaml
