{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-manager-role
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
  # Keycloak resources
  - apiGroups:
      - keycloak.hostzero.com
    resources:
      - keycloakinstances
      - keycloakrealms
      - keycloakclients
      - keycloakusers
      - keycloakclientscopes
      - keycloakgroups
      - keycloakidentityproviders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Status subresources
  - apiGroups:
      - keycloak.hostzero.com
    resources:
      - keycloakinstances/status
      - keycloakrealms/status
      - keycloakclients/status
      - keycloakusers/status
      - keycloakclientscopes/status
      - keycloakgroups/status
      - keycloakidentityproviders/status
    verbs:
      - get
      - patch
      - update
  # Finalizers
  - apiGroups:
      - keycloak.hostzero.com
    resources:
      - keycloakinstances/finalizers
      - keycloakrealms/finalizers
      - keycloakclients/finalizers
      - keycloakusers/finalizers
      - keycloakclientscopes/finalizers
      - keycloakgroups/finalizers
      - keycloakidentityproviders/finalizers
    verbs:
      - update
  # Secrets (for credentials and client secrets)
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Events (for recording events)
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # ConfigMaps and Leases for leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- end }}
