[book]
authors = ["HostZero"]
language = "en"
src = "src"
title = "Keycloak Operator"

[output.html]
git-repository-url = "https://github.com/Hostzero-GmbH/keycloak-operator/"
edit-url-template = "https://github.com/Hostzero-GmbH/keycloak-operator/edit/main/docs/{path}"
