[book]
authors = ["HostZero Team"]
language = "en"
multilingual = false
src = "src"
title = "Keycloak Operator Documentation"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/hostzero/keycloak-operator"
edit-url-template = "https://github.com/hostzero/keycloak-operator/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1
